system:
  # Used to create virtual envs, install dependencies for Rasa. Usually, Rasa does not support the latest Python version.
  rasa_preferred_python_version: "3.9"

bot_engine: "rasa"

rasa:
  rest_webhook: "http://localhost:8002/webhooks/rest/webhook"
  expected_launch_duration_sec: 30  # to avoid opening the browser-UI too early

server:
  port: 8000
  address: "localhost"
  static_files_dir: "./dist"
  db_path: "../db/replica.db"

