# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# See https://rasa.com/docs/rasa/tuning-your-model for more information.
pipeline:
  - name: SpacyNLP
    model: "en_core_web_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  # using n-grams provides better resiliency to typos
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 2
    max_ngram: 4
  # DIETClassifier perfoms intent recognition and entity extraction.
  # intent recogniton is traned on user data
  # entity extraction is trained on user data
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    use_masked_language_model: true
    # embedding_dimension: 30
    # transformers_layers: 4
  # pre-trained entities
  - name: SpacyEntityExtractor
    # dimensions to extract
    # dimensions: ["PERSON", "LOC", "GPE", "ORG", "PRODUCT"]- 
  - name: EntitySynonymMapper
  - name: ResponseSelector
    constrain_similarities: true
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 10 # the higher the value, the better the prediction of the next action
    epochs: 100
    constrain_similarities: true
